### ISSUE TITLE
v3.0.0 breaks on MacOS X with Python 2.7

### ISSUE THREAD

**Issue by ajmas** [basilfx/flask-daapserver#1]
Just tried installing on MacOS X 10.10, running Python 2.7 from MacPorts and I run into an install failure. Cloning the git repository and then switching to the v2.3.0 tagged release resolved the build issue and resulted in a successful install. The v3.0.0 tagged release & HEAD results in the same failure. The failure details:

```
Processing /Users/ajmas/Development/third-party/flask-daapserver
Complete output from command python setup.py egg_info:

Error compiling Cython file:
------------------------------------------------------------
...
def login(provider, session_id):
    """
    Generate a login response.
    """

    return DAAPObject("dmap.loginresponse", [
                    ^
------------------------------------------------------------

daapserver/responses.pyx:9:21: Compiler crash in DAAPObjectTransformer

ModuleNode.body = StatListNode(responses.pyx:1:0)
StatListNode.stats[1] = DefNode(responses.pyx:4:0,
    doc = u'\n    Generate a login response.\n    ',
    modifiers = [...]/0,
    name = u'login',
    num_required_args = 2,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0')
DefNode.body = StatListNode(responses.pyx:5:4)
StatListNode.stats[0] = ReturnStatNode(responses.pyx:9:4,
    is_terminator = True)
ReturnStatNode.value = SimpleCallNode(responses.pyx:9:21,
    result_is_used = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 173, in Cython.Compiler.Visitor.TreeVisitor._visit (/opt/local/var/macports/build/_opt_mports_dports_python_py-cython/py27-cython/work/Cython-0.21.2/Cython/Compiler/Visitor.c:4449)
    return handler_method(obj)
  File "/tmp/pip-s0X1cO-build/utils/transformer.py", line 26, in visit_CallNode
    node.function.name = self.context.intern_ustring(
AttributeError: 'Context' object has no attribute 'intern_ustring'
Compiling daapserver/daap.pyx because it changed.
Compiling daapserver/revision.pyx because it changed.
Compiling daapserver/collection.pyx because it changed.
Compiling daapserver/models.pyx because it changed.
Compiling daapserver/responses.pyx because it changed.
Cythonizing daapserver/collection.pyx
Cythonizing daapserver/daap.pyx
Cythonizing daapserver/models.pyx
Cythonizing daapserver/responses.pyx
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "/tmp/pip-s0X1cO-build/setup.py", line 44, in <module>
    "daapserver/responses.pyx",
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 840, in cythonize
    cythonize_one(*args[1:])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 959, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: daapserver/responses.pyx
```

**Comment by basilfx** [comment]
Thank you for reporting this. 

Can you check your Cython version? I would recommend the latest one.

**Comment by basilfx** [comment]
I have improved the `setup.py` script to check the installed Cython version. The problem is that `setup.py` depends on Cython during setup. I had to implement my own checks, but forgot to check for the proper version.

Please check it out via `pip install git+https://github.com/basilfx/flask-daapserver -U`. Travis build passes.

**Comment by ajmas** [comment]
Just tried and this made it clear I was using and older version of Cython. I verified and I indeed was using Cython 2.1. Upgraded to Cython 2.3 and now install is successful.

Thanks for this.
